[colors.primary]
background = '#181818'
foreground = '#E0E0E0'

[colors.normal]
black   = '#212121'
red     = '#E06D76'
green   = '#66BB6A'
yellow  = '#FFEE58'
blue    = '#5F97F6'
magenta = '#9575CD'
cyan    = '#26C6DA'
white   = '#E0E0E0'

[colors.bright]
black   = '#757575'
red     = '#E57373'
green   = '#81C784'
yellow  = '#FFF176'
blue    = '#79A7F8'
magenta = '#AF8EEC'
cyan    = '#4DD0E1'
white   = '#FFFFFF'

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window.padding]
x = 32
y = 32

[window]
opacity = 0.75
